### ISSUE TITLE
ctl.h: No such file or directory

### ISSUE THREAD

**Issue by rem4332** [sarnau/LoxLink#12]
Ich hab mich an das Build gemacht aber leider findet er die ctl.h nicht.
Leider bin ich noch sehr grün hinter den Ohren mit dem Zeugs. 
Woher bekomme ich denn diese?

Vielen Dank

**Comment by sarnau** [comment]
Teil der libctl von Rowley Crossworks.

**Comment by rem4332** [comment]
Danke habs gefunden.
