### ISSUE TITLE
Tree Device

### ISSUE THREAD

**Issue by chrisrock1984** [sarnau/LoxLink#14]
Hi,
Ich habe mal versucht ein Tree Device zu kompilieren. Es ist aber nur möglich, wenn auch die Tree Extension mit kompiliert wird.
Ist es also richtig, dass man kein Tree Device stand-alone kompilieren kann?

**Comment by sarnau** [comment]
Ja, den Fall habe ich nie implementiert – ist aber machbar. Ich sehe denn Sinn nicht, denn man kann dem Miniserver ja mehr als eine Tree Extension unterschieben und somit einfach diverse Tree Devices und die Extension auf einem STM32 simulieren.

**Comment by chrisrock1984** [comment]
Nur für den unwahrscheinlichen Fall, dass man mehrere Tree Devices baut und die maximale Anzahl an LoxBus devices überschreitet ;-)

**Comment by challo2018** [comment]
Ich habe auch versucht nur ein Tree device zu kompilieren. funktioniert bei mir problemlos und es wird auch auf dem tree bus von der tree extension erkannt. allerdings bekomme ich nach einiger zeit das authentifizierungsproblem angezeigt...

**Comment by sarnau** [comment]
Was meinst Du mit "einiger Zeit"? Tage? Wochen? Monate? :-)

**Comment by challo2018** [comment]
Minuten. Sorry wegen der ungenauen Angabe...

**Comment by chrisrock1984** [comment]
Kann ich bestätigen. 
Wenn ich aber nur die Tree Extension einfüge ohne Tree Device funktioniert es. Sobald ich aber das Tree Device suche und hinzufüge bekomme ich viele Fehler sowie den Authentication Error.

**Comment by challo2018** [comment]
Ich hab das ganze ohne tree Extension direkt auf dem tree Bus getestet. Wird problemlos erkannt aber dann kommt der authentication Fehler

**Comment by chrisrock1984** [comment]
Wie, du betreibst dein STM32 board als Tree Device? Verstehe ich das richtig, dass du eine originale Tree Extension hast und dein Board hängt am Tree Bus?

**Comment by challo2018** [comment]
Genau hab das Board auf den Tree Bus hinter einer original Extension gehängt. 
Folgende Anpassungen habe ich gemacht in der main:

static LoxCANDriver_STM32 gLoxCANDriver(**tLoxCANDriverType_TreeBus**);

static LoxBusTreeAlarmSiren gLoxBusTreeAlarmSiren(**gLoxCANDriver**, 0xb010035c, gResetReason);

Das Gerät wird dann erkannt und kann auch über die Tree Geräte Suche in der Loxconfig hinzugefügt werden

**Comment by chrisrock1984** [comment]
Das probier ich gleich mal aus ;-)

**Comment by chrisrock1984** [comment]
CAN H = grün, oder?
Ich hoffe, dass **DER Guru** noch die Authenticate Probleme löst ;-)

**Comment by challo2018** [comment]
Kann gerade nicht nachschauen. Ich habs einfach ausprobiert. Sollte nichts passieren wenn man es vertauscht.

Wäre cool wenn du es auch mal testen könntest! Bei der AlarmSirene ist vielleicht noch wichtig das der Sabotage Kontakt als Okay gesendet wird. Ansonsten meldet Loxone Sabotage.
-> hardwareTamperStatusOk

**Comment by chrisrock1984** [comment]
Gerade getestet - Auth. Fehler nach ca 1 Min.
Nach dem Neustart sagt die Tree Diagnose auch, dass 100% der Pakete verloren gegangen sind, obwohl das Tree Device ordnungsgemäß erkannt wurde.

**Comment by challo2018** [comment]
Super, vielen Dank! Dann hab ich erstmal nichts falsch gemacht. Wäre echt super wenn wir hier den Fehler finden könnten.

**Comment by chrisrock1984** [comment]
Könnte man das "issue" wieder auf Open setzen?

**Comment by sarnau** [comment]
Die Authorization Issue gibt es noch "offen". Dies ist somit ein Dupe

**Comment by challo2018** [comment]
@sarnau Können wir irgendwie bei der Fehleranalyse unterstützen?

Hier gehts dann weiter:
#8

**Comment by chrisrock1984** [comment]
Genau, helfe auch gerne mit ;)
