### ISSUE TITLE
random_range overflows

### ISSUE THREAD

**Issue by MarekFort** [sarnau/LoxLink#24]
Hi,
I was debugging the code and found out that random_range() fails due to uint16 overflow.
There is this code (global_functions.cpp line 17)
`uint16_t range = maximum - minimum + 1;`

and LoxLegacyExtension.cpp calls it with maximum 0xffff and minimum 0.
So the range gets 0 due to oveflow.

Then line fails:
`return value % range + minimum;`
 
because of modulo by 0.

Making the range uint32_t fixes the problem.

**Comment by sarnau** [comment]
Good catch. Thanks.
