### ISSUE TITLE
Authentifikation fehlgeschlagen

### ISSUE THREAD

**Issue by matlab22** [sarnau/LoxLink#3]
Ich habe es nun geschafft die Di Extension in Betrieb zu nehmen. Die Freude war aber von sehr kurzer Dauer. Loxone wollte die Extension von 10.02.02.28 auf 10.03.11.08 aktualisieren. Dies ist logischerweise fehlgeschlagen. Damit er diese nicht aktualisieren will habe ich die Versionsnummer in LoxBusDIExtension.cpp auf 10031108 geändert. Worauf hin Loxone einene Meldung gebracht hat und die Extension deaktivert hat. 
![Screenshot_2020-01-19-17-47-25-084_com loxone kerberos](https://user-images.githubusercontent.com/46869303/72684990-bc579680-3ae5-11ea-9bde-5972e83cbac7.png)
Vorher hatte ich noch kurz einen Eingang unter der alten Versionsnummer testen können :)

Hast du einen Tipp wie man diese Authentifikation vorgaukeln kann?

**Comment by sarnau** [comment]
Ok, aktuell mußt Du 10.2 nutzen, nicht die 10.3. Dann funktionieren alle Extensions und Devices.

**Comment by sarnau** [comment]
Ich habe gerade Support für Authorization gepusht.
