### ISSUE TITLE
DMX Extension Authentication Fail

### ISSUE THREAD

**Issue by matlab22** [sarnau/LoxLink#7]
Sobald ich der DMX Extension Aktoren zuweise kommt das Autentifizierungsproblem wieder :(
Kann es sein, dass die Legacy sich doch etwas anders autentifizeren?
Habe ich es falsch verstanden, dass LoxLegacyDMXExtension von der LoxLegacyExtension erbt und sich die Methode FragmentedPacketToExtension um den Crypto-Key kümmert? Muss ich noch etwas anderes beachten, dass ich eventuell übersehen habe?

**Comment by sarnau** [comment]
Ja, tun sie. Der Algorithmus ist völlig gleich, wird aber via dem Legacy-Fragmented-Package übertragen. Ich habe den DMX Code noch nicht selbst ausprobiert, habe es nur mit der Relay-Extension ausprobiert.

**Comment by chrisrock1984** [comment]
> Sobald ich der DMX Extension Aktoren zuweise kommt das Autentifizierungsproblem wieder :(
> Kann es sein, dass die Legacy sich doch etwas anders autentifizeren?
> Habe ich es falsch verstanden, dass LoxLegacyDMXExtension von der LoxLegacyExtension erbt und sich die Methode FragmentedPacketToExtension um den Crypto-Key kümmert? Muss ich noch etwas anderes beachten, dass ich eventuell übersehen habe?

Welche Pins werden für den RS485 Transceiver verwendet? Im Code habe ich leider nichts gefunden, oder wahrscheinlich übersehen.

**Comment by sarnau** [comment]
Kann mich nicht mehr erinnern, aber RS485 wird wie RS232 angesteuert. Ist quasi identisch.

**Comment by chrisrock1984** [comment]
Eine andere Frage - Ist die Implementierung der DMX Extension auch funktional? Ich habe mir den Code der Modbus sowie der RS232 Extension angesehen. Dort findet sich Code für den HW Zugriff. Dei der DMX Implementierung habe ich das nicht gefunden.
Bitte um Richtigstellung ;-)

Danke!!

**Comment by sarnau** [comment]
Nein, ich habe nicht alle Extensions und Geräte nachprogrammiert. Gerade DMX braucht ja eine spezielle RS485 Ansteuerung mit fixem Timing.

**Comment by chrisrock1984** [comment]
Gut ;) Ich kann noch Code lesen! Danke für die Info!
